---
title: "Scientific Question (Assn. 1)"
---

Study Design Assignment 1: Matching your scientific question to the best study design and preventing information bias. Provide a concise but complete response (At least 2, but not more than 4 pages) to the following questions.

## Describe 3 scientific questions/hypotheses that you would be interested in investigating through an epidemiologic study. One or two sentences for each question is sufficient.
 
a. Do mobile treatment units for Methadone increase the access to care for people with OUD? This might be hard to asses but I think it's worth coming up with something because it's really the core of effort to get better treatment to more people. Sub-question: does this results in fewer adverse events?

b. Do mobile treatment units change the demographics of people receiving methadone? The demographics of the opioid epidemic are complex and have shifted since it began with working class in whites in deindustrialized areas making up the majority of cases and other groups becoming more involved more over time. Monitoring for demographic shifts could help asses if the programs were helping in a fair way.

c. Do mobile treatment units results in fewer cases of COVID among people with OUD? One think worth interrogating is if switching to the vans would help at all. If not, it might make sense to divert resources back to the initial clinics. If it reduces infections, it could serve as a treatment model for other diseases.

## Choose one of the scientific questions that you have proposed above and answer the following questions. (Though you may change your study question later)

a. What is your conceptual exposure? Is this exposure rare or common?

My exposure is opioid use disorder in a region where MTUs are being explored as a potential treatment delivery system. It's rare compared to something like cardiovascular disease, and I don't think it's greater than 20% of the population (the rough rule we're using for this class) [double check]. It is increasingly common however, having become the leading cause of accidental death [find where I read this].

b. What is your conceptual outcome? Is this outcome rare or common?

The outcome would be receiving medication-based treatment for opioid use disorder via a MTU (let's say, >10% of the time)[note: might need to workshop this]. It would also make sense to track adverse events like hospitalizations, overdoses, and deaths.

c. Briefly describe how you might use each of the four major study designs in epidemiology (cohort, case-control, cross-sectional (or ecologic if you like), or randomized trial) to assess this question. For purposes of this exercise, I’d like you to stretch your ideas about study design, so do your best to come up with a way to use every one of the study designs to address your question of interest. Feel free to be a bit creative for this part of the question (you will assess feasibility and logistics in the next part of the question).

    - Cohort: In this design, we could enroll people based on their opioid use disorder status and the policy of the closets methadone clinic (if they use vans or not). After the enrollment, we would follow them for a designated period. We could then asses a variety of metrics like adherence, overdoses, or death. The main one would be adherence, defined as people who reported to the van. We could then compare this to the rates in the people who didn't have the van option. This would be the prospective option. For the retrospective version, we could attempt to find data on overdoses, demographics, etc from historical database. We could then see if people in the MTU regions different in terms of endpoints.

    - Case control: This ones stretches my proposal quite a bit. I need to think on it [return to this]. In this we would need to define a different endpoint, let's say overdose. We could enroll people in a non-MTU region as controls and a MTU region as cases. We could follow them and see if they different on our endpoints. OUD is likely uncommon enough that odds ratio would approximate the risk.

    - Cross-sectional: In this method, we might obtain interview or medical records. We would asses the desired information on demographics and outcomes. We could review the records to see if subjects had an overdose, etc. The advantage here is that it's the cheapest and fastest. The downside is that we wouldn't have continuity in terms of time and would have very little control over confounding.

    - Randomized trial: In this version of the study we would randomly assign people to treatment regions where MTUs were available and some to those where they weren't. This would be extremely difficult logistically because the point of the MTUs is to address access, and assigning people to facilities other than the closest one would be prohibitive. Perhaps it would be possible to assign the MTU programs randomly as pilot programs instead of using the places where it was already in use. 


## Focus in on what is pragmatic or logistically possible to answer the following questions about your scientific question and study design.

a. Which study design from part 2c seems most feasible? Why does this design seem
best for addressing your scientific question?

I think there are two that could work here, the cohort and the cross-sectional study. The cohort would be more ambitious - it would require following people who might be at higher risk for housing instability over a long period of time if the prospective option was used. If the data were available already, it could be approached retrospectively. This might be the most practical option in terms of balancing feasibility with robustness.

The cross-sectional might be the best we could do if the data were only available as a snapshot.

b. What will you use as your operational exposure and outcome? Or what are some
reasonable options for operational exposure and outcome? Note that this should
match up to the study design you’ve identified as most feasible in 3a.

Let's assume we can do a retrospective cohort study. In this case the operational exposure would be a medical record reporting use of illegal opioids. The patients would then be categorized as having used a MTU for medical treatment of OUD or having used a traditional clinic. The outcome would be reporting to the ER with an overdose or a fatality.  

c. What other data will you need to collect for you study (i.e., what are the important
covariates for your study)?

Given the complex demographic makeup of the opioid crisis[@cerdaCriticalReviewSocial2021], it would be crucial to collect information such as race and sex, and given the variation in risk with employment and education, information on work and schooling. Geographic information may be required as well.

## Place your chosen question into the broader context of the existing literature.

a. Identify 2-4 relevant papers from the primary literature to provide background and
motivation for your proposed study. Provide the citations and a 1-2 sentence
summary of the critical background information contained in each study.

Joudrey PJ, Edelman EJ, Wang EA, "Methadone for Opioid Use Disorder—Decades
of Effectiveness but Still Miles Away in the US" [@joudreyMethadoneOpioidUse2020] provides evidence of the effectiveness of methadone as well as background on the restrictions around using it. It also contextualizes status quo by discussing the political and policy factors that created it. 

Cerdá M, Krawczyk N, Hamilton L, et al, "A Critical Review of the Social and Behavioral
Contributions to the Overdose Epidemic" [@cerdaCriticalReviewSocial2021] provides and exhaustive overview of epidemic with a focus on the demographic and policy aspects. It also includes a history of the epidemic and an analysis of economic drives of supply and demand of drugs.

Jakubowski A, Fox A, "Defining Low-threshold Buprenorphine Treatment" [@jakubowskiDefiningLowthresholdBuprenorphine2020] specifically discusses the barriers to entry in pursuing medication-based treatment for OUD. It's main contribution is a definition of and argument for treatment policies that emphasize making treatment more easy to get.

Chan B, Hoffman KA, Bougatsos C, et al "Mobile methadone medication units: A brief history, scoping review and research opportunity" [@chanMobileMethadoneMedication2021a] describes the history of mobile treatment units. It also lays out the case for using them as an opportunity to asses drug-based treatments. In particular, because they are becoming legal and being tested, we will now when the change was adopted for comparison.


b. What knowledge gap does your proposed study address? (i.e., Will it add to our scientific knowledge by answering a completely new question? Will it help us understand a new mechanism to explain a previously observed association? Will it
extend the research to a new population?)

My proposed study would asses the demographics of those who seek medication-based treatment for OUD in a mobile setting. This would offer insights into what communities benefit the most, if there is a disparity. This would highlight needs for future work. If the vans are broadly effective and demographics do not show a disparity, it would confirm their value. It could also interrogate the utility in improving outcomes. The demographics would be a new contribution as would the outcomes. The benefit of medication assisted treatment in general is well established and would not be a contribution.

## Are there any relevant sources of information bias to consider for your study as designed (consider all potential types of information bias)? How might you prevent these or improve exposure/outcome/covariate data collection to minimize these concerns?