
# Study Description

I propose a study of the impact of mobile treatment vans for methadone delivery to people with opioid use disorder (OUD). A large body of evidence spanning decades supports the use of Methadone (also called Methadone and Dolophine) for treatment of OUD [@joudreyMethadoneOpioidUse2020]. Despite this, the majority of people suffering from the disorder do not get medication-based treatment [@cerdaCriticalReviewSocial2021]. By law Methadone treatment can only be conducted by specially-licensed practitioners and those in treatments are required to report to the clinic every day to get the treatment, at least initially [@joudreyMethadoneOpioidUse2020]. These policies have been implicated as barrier to treatment [@jakubowskiDefiningLowthresholdBuprenorphine2020]. The start of the pandemic caused a wave of logistical restructuring across field, including healthcare, and the use of mobile treatment units (MTUs) that can bring medications to people by van was considered as an option to improve access[@krawczykLessonsCOVID192020]. A growing line of research asses the effectiveness and feasibly of this treatment modality[@chanMobileMethadoneMedication2021a].   